FROM arm64v8/ros:noetic
USER root
ENV user=jetson
ENV password=jetson
RUN mkdir /home/${user} \
    && useradd -rm -d /home/${user} -s /bin/bash  ${user} \
    && adduser ${user} sudo \
    && echo "${user}:${password}" | chpasswd \
    && echo "${user} ALL = NOPASSWD: ALL" >> /etc/sudoers \
    && ln -s /usr/bin/empy3 /usr/bin/empy \
    && apt-get update && apt-get install -y \
    vim \
    ros-noetic-desktop-full \
    ros-noetic-serial \
    ros-noetic-teleop-twist-joy \
    ros-noetic-navigation \
    ros-noetic-depthimage-to-laserscan \
    ros-noetic-rgbd-launch \
    ros-noetic-libuvc-camera \
    ros-noetic-libuvc-ros \
    libgoogle-glog-dev
    

COPY ./  /home/${user}/FritzRobot_docker
RUN chmod -R a+x /home/${user}/FritzRobot_docker
USER ${user}
WORKDIR /home/${user}
ENTRYPOINT ["sudo", "bash","./FritzRobot_docker/ros_entrypoint.sh"]


