FROM amd64/ros:noetic
USER root
ENV user=jsy
ENV password=jsy
RUN mkdir /home/${user} \
    && useradd -rm -d /home/${user} -s /bin/bash  ${user} \
    && adduser ${user} sudo \
    && echo "${user}:${password}" | chpasswd \
    && echo "${user} ALL = NOPASSWD: ALL" >> /etc/sudoers \
    && ln -s /usr/bin/empy3 /usr/bin/empy \
    && apt-get update && apt-get install -y \
       ros-noetic-serial \
       ros-noetic-teleop-twist-joy \
       ros-noetic-joy

COPY ./  /home/${user}/FritzRobot_docker
RUN chmod -R a+x /home/${user}/FritzRobot_docker
USER ${user}
WORKDIR /home/${user}
ENTRYPOINT ["sudo", "bash","./FritzRobot_docker/ros_entrypoint_x86_64.sh"]


