
version: '2'
services:
  ros-noetic:
    privileged: true #为了把设备挂载到容器，需要privileged的权限
    tty: true
    devices:
      - /dev:/dev
    build:
      context: ../
      dockerfile: Dockerfile_x86_64
    volumes:
      - /home/jsy/catkin_ws:/home/jsy/catkin_ws
    network_mode: "host"

