
version: '2'
services:
  ros-noetic:
    platform: linux/arm64/v8
    privileged: true #为了把设备挂载到容器，需要privileged的权限
    tty: true
    devices:
      - /dev:/dev
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
<<<<<<< HEAD
      - /home/jsy/catkin_ws:/home/jsy/catkin_ws
    ports:
      - "11311"
=======
      - /home/jetson/catkin_ws:/home/jetson/catkin_ws
>>>>>>> c509fb8e668eb546fbf1d6a6403e1f59c979ffab


